name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: apt install ocaml

    - name: Compile Lab
      run: make lab2
      
    - name: Test Lab
      run: ./lab2
